/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as counterSol from './Counter.sol/index.js';
export type { counterSol };
import type * as soulboundNftSol from './SoulboundNFT.sol/index.js';
export type { soulboundNftSol };
export * as factories from './factories/index.js';
export type { Counter } from './Counter.sol/Counter.js';
export { Counter__factory } from './factories/Counter.sol/Counter__factory.js';
export type { SoulboundNFT } from './SoulboundNFT.sol/SoulboundNFT.js';
export { SoulboundNFT__factory } from './factories/SoulboundNFT.sol/SoulboundNFT__factory.js';